use_frameworks!

target 'MDSWebViewController_Example' do
  pod 'MDSWebViewController', :path => '../'

  target 'MDSWebViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
